spring.application.name=logisticsmanagementsystem
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/logisticsmanagementsystem
spring.datasource.username=postgres
spring.datasource.password=root
#Email
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vemulaniharika52@gmail.com
spring.mail.password=xgrhwcvmmlcbfwtu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=mysecretkeymysecretkeymysecretkey
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect